language: go

go:
    - 1.5

before_install:
    - sudo apt-get install nodejs npm
    - npm install

install:
    - go get -u github.com/gopherjs/gopherjs
    - gopherjs get github.com/gopherjs/jsbuiltin
