language: go

go:
    - 1.5

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install nodejs npm
    - npm install

install:
    - go get -u github.com/gopherjs/gopherjs
    - go get -u -d -tags=js github.com/gopherjs/jsbuiltin

script:
    - diff -u <(echo -n) <(gofmt -d ./)
    - gopherjs test
